name: learn-github-actions
on: [push]
jobs:
  install-and-check-go-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from git repository
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Show go version
        run: go version
